### ISSUE TITLE
The last four audio at the bottom of the "Space & Autonomy" open up in new tab

### ISSUE THREAD

**Issue by pradyumnat** [janastu/ncbs-omeka-backbone-client#16] opened 2016-10-24 13:14 UTC

**Comment by vns2** [comment] 2016-10-26 08:26
These should be part of Gallery, and ideally, a box for 'Gallery' opens up in a new tab. Perhaps simpler?

**Comment by salus-sage** [comment] 2016-10-26 18:18
Duplicate of issue #48 
@vns2 the request will be addressed in this milestone.

**Closed as completed by salus-sage** 2016-10-26 18:18 UTC
