### ISSUE TITLE
"Institution Building" foot text and the icon panel body doesn't fit on the equal 

### ISSUE THREAD

**Issue by pradyumnat** [janastu/ncbs-omeka-backbone-client#13] opened 2016-10-24 13:14 UTC

**Comment by salus-sage** [comment] 2016-10-26 18:28
This needs a real look around from the content sme @vns2 or the designer. basically we are struggling with more words than we can accommodate. out of scope for developers to fix. needs discussion

**Comment by vns2** [comment] 2016-10-27 09:52
What is this referring to? The words "Institution Building" in the big square icon at the bottom? If so, not sure where the problem is. Can you clarify? Thanks!

**Comment by salus-sage** [comment] 2016-10-27 14:31
The word length "Institution Building" exceeds the accommodated space from the original design spec(which only has Institution). Hence there is mis-behaviour(an increase in the height of the box) in certain browsers(mostly IE 7 & 8) and/or screens(of lesser widths), to resolve we either need to re-work the word or the icons itself.

**Comment by vns2** [comment] 2016-10-28 05:07
Understood. Two options:
1) I have attached one option - does this work or will it create problems and increase in height as well? I moved the icons up and put the two words staggered around the midline. Dont want to overthink this. 
2) Try just 'Building' instead of Institution Building. What are your thoughts? Do you think it captures the idea of 'institution building'. Not able to come up with any other single word yet. But this 'Building' is a compromise for Beta release and I am okay with it.

![two themes](https://cloud.githubusercontent.com/assets/4581081/19795310/2fc14fd8-9cf8-11e6-96ea-01d7bc48f373.png)

**Comment by vns2** [comment] 2016-11-17 04:28
@salus-sage Forgot to ask, does this work?

**Comment by salus-sage** [comment] 2016-11-22 10:25
fixing the width of containers to make it a fixed width website. 
issue only repeats at min zoom 25%(considering as an exception) tested upto 300% zoom(no mis-behaviour)
closing as Issue resolved

**Closed as completed by salus-sage** 2016-11-22 10:25 UTC
