### ISSUE TITLE

collabeation - last three audio are opening in new tab first image comes after reloading the page, in firefox

### ISSUE THREAD

**Issue by pradyumnat** [janastu/ncbs-omeka-backbone-client#39] opened 2016-10-26 10:32 UTC

**Comment by salus-sage** [comment] 2016-10-26 18:01
Audio problem is duplicate of issue #48 
image problem tested in Firefox version 49.0.2 - no obvious problem, needs more description

**Comment by salus-sage** [comment] 2016-10-26 18:02
image problem referred in issue #37

**Closed as completed by salus-sage** 2016-10-26 18:02 UTC
