### ISSUE TITLE
chromium

### ISSUE THREAD

**Issue by Amrapalivishwa** [janastu/ncbs-omeka-backbone-client#60] opened 2016-11-07 09:26 UTC
peopleplex some of the nodes are not loading or opening, which are oprning in firefox, but in firefox audio overlaps. no overlap of audio  in chromium.

**Comment by salus-sage** [comment] 2016-11-07 10:12
please submit screenshot with your mouse pointer pointing to the nodes you are mentioning.

**Comment by salus-sage** [comment] 2016-11-11 13:23
@Amrapalivishwa i'm waiting for a screenshot

**Comment by vns2** [comment] 2016-11-16 10:00
I found the following nodes as shown in attached image to be dead in Chrome v54 (top row, four nodes). The 'content' hidden changes as you click on different nodes -- the toroid rotates slightly, usually clockwise. 

In addition, whatever I do, I am not able to get the content for three people in any config:
Obaid Siddiqi (should be near nodes of Zakir Hussain and Riayat Khan)
Umashashi (should be near Meena Srinivasan and Shaju Varghese)
T Eswar (should be near GH Mohan and SN Basha).

![chrome_peopleplex_nodes-not-working](https://cloud.githubusercontent.com/assets/4581081/20342674/65d1902e-ac11-11e6-976e-e3f915df091e.png)

**Comment by salus-sage** [comment] 2016-11-21 09:35
duplicate of issue #68

**Closed as completed by salus-sage** 2016-11-21 09:35 UTC
